# Generated by Django 2.2.2 on 2019-07-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='tutorial_product_sales',
        ),
    ]
